### PR TITLE
Updated to Ember CLI 1.13.13

### PR DESCRIPTION
**Pull request by Baltazore**
Upgraded all files thought `ember init` diff with defaults from Ember CLI 1.13.11.
Ember and Ember Data versions left unchanged.

Thank you for the great work and contribution to the Ember community :+1:

### CODE REVIEW

**Comment by bcardarella** [comment]
Are we certain that the release issues for 1.13 are solved? I saw three releases done in an hour earlier today

**Comment by Baltazore** [comment]
@bcardarella let's wait for day or two, and leave this PR open. I will continue upgrading this branch until Ember CLI become stable.

**Comment by drspaniel** [comment]
Seems they settled on `1.13.12`.
@bcardarella looks good to me!

**Comment by bcardarella** [comment]
@Baltazore this did not merge cleanly for whatever reason. I've reverted the commit. Travis was failing after merge with `master`.

**Comment by Baltazore** [comment]
I will check it. Thanks

**Comment by bcardarella** [comment]
@Baltazore thanks! Once green I'll happily merge :smile:

**Pull request merged**
