### PR TITLE
Add computed properties based on state

### PR DESCRIPTION
**Pull request by rsocci**
* Add ember version 1.13 to ember-try
* Rename `textState` to better reflect what the variable holds
* Add `htmlbars-inline-precompile` since this is included by default
 in new ember-cli addons

done with @drspaniel

### CODE REVIEW

**Comment by rsocci** [comment]
Addresses root issue of: https://github.com/dockyard/ember-async-button/issues/38

**Comment by drspaniel** [comment]
@danmcclain :eyes:?

**Comment by bcardarella** [comment]
That's interesting. @rwjblue and I had discussed a while bad a way to do state handling with the handlebars templates:

```handlebars
{{#async-button foo=bar}}
  Resolved...
{{pending}}
  Pending...
{{rejected}}
  Rejected...
{{/async-button}}
```

@rwjblue do you recall ^ ?

**Comment by drspaniel** [comment]
I think our solution is simple enough for people to get. As is it's an incredibly simple add-on, and I think that's a benefit - I'm not sure there's a need for this kind of DSL here. All that buys people is not having to put `{{#if}}` in their templates I think.
@bcardarella Do you think it's worth the complexity trade-off?

**Comment by bcardarella** [comment]
I've given this some thought and this is not the direction I want the library to go. As I've already stated, the template states are what I want to do and do not want to introduce API that would be otherwise.

**Pull request closed without merging**
