### PR TITLE
use new modules api

### PR DESCRIPTION
**Pull request by Dhaulagiri**

### CODE REVIEW

**Comment by bcardarella** [comment]
I'm :-1: on this as it breaks backwards compatibility

**Comment by Dhaulagiri** [comment]
@bcardarella my understanding (and anecdotal experience) is that compatibility is based on the version of ember-cli-babel the addon ships with.  Is there some other incompatibility that I'm not aware of?

**Comment by bcardarella** [comment]
@Dhaulagiri you are correct, apologies. LGTM :)

**Comment by Dhaulagiri** [comment]
@bcardarella at your convenience could we get a release cut with this change in it?

**Comment by bcardarella** [comment]
@Dhaulagiri we are planing on deprecating this addon so no new releases will be produced. We will be blogging about this as well as a migration path away from this addon in the near future.

**Comment by Dhaulagiri** [comment]
That makes sense.  If it's not too much work it'd be nice to have a final release with the latest changes in it while we wait to migrate, but it's not a _huge_ deal.

**Pull request merged**
